# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ExampleProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleProject
  # pod 'AppruveiOSSDK', '~> 0.0.8'

  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'SwiftyJSON', '~> 4.0'

  target 'ExampleProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleProjectUITests' do
    # Pods for testing
  end
end
